// CONTACT TYPES
export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const FILTER_CONTACTS = "FILTER_CONTACTS";
export const CLEAR_FILTER = "CLEAR_FILTER";

// ACTIVITY TYPES
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const SET_CURRENT_ACTIVITY = "SET_CURRENT_ACTIVITY";
export const CLEAR_CURRENT_ACTIVITY = "CLEAR_CURRENT_ACTIVITY";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";
export const FILTER_ACTIVITIES = "FILTER_ACTIVITIES";
export const CLEAR_FILTERED_ACTIVITIES = "CLEAR_FILTERED_ACTIVITIES";